### ISSUE TITLE
Strange Markers

### ISSUE THREAD

**Issue by tayldn** [OrdnanceSurvey/openspace-android-sdk#1]
Hoping you can help with some questions we have setting up the SDK please?
Can you help with this question please?

I use a custom InfoWindowAdapter for Info Window. All Info Windows for markers have strange anchor.
Why? How can I change anchor for them?

There are some screenshots for different markers.
1st – use customized Info Window  (Nexus 5 /  Android 5.0) 2nd – use default Info Window (Nexus 5 /  Android 5.0) 3rd – use default Info Window (Nexus 10 /  Android 4.4.4)

_______________________

OS Response:
The info window anchor cannot currently be set independently. It should be tied to the GridPoint used to set the marker position.

Looking at the images you sent it looks like the info window is anchored to the right hand edge of the marker icon.

Can you send me a code snippet showing your marker options and marker creation and I'll see if I can replicate the issue and find you a solution.
_____________________________

My answer:
                No, I use parameter  .anchor(0.5f, 1.0f). I have test different parameters. All look bad too.
                I have tested demo app from your samples – it looks bad too.

               1-3 screenshots: test with different conditions (Custom Marker / Default Marker & Default Info Window // Custom Info Window)
4th           screen – test with route and start/finish markers with different anchors (on screen without snippet, with snippet it looks worse); for test one marker uses .anchor(0.5f, 1.0f), second - .anchor(0.0f, 0.0f)

Test code from demo:

private void showTestRoute(){

//* ArrayList  initialization
    * ….
   */
        PolylineOptions pOptions = new PolylineOptions();
        pOptions.color(getResources().getColor(android.R.color.holo_red_dark));

        final MapProjection projection = MapProjection.getDefault();
                // add Route

        for(LatLng ll : coords){

                pOptions.add(projection.toGridPoint(ll.latitude, ll.longitude));

        }

        mMap.addPolyline(pOptions);

                // move camera to Start Point

        GridPoint startPoint = pOptions.getPoints().get(0);

        mMap.moveCamera(new CameraPosition(startPoint, 0.5f), false);

                // show Markers

        BitmapDescriptor icon = BitmapDescriptorFactory.defaultMarker();

        mMap.addMarker(new MarkerOptions()

                .gridPoint(MapProjection.getDefault().toGridPoint(55.935753000000, -4.562352000000))

                .title("Start point")

//                    .snippet(locationMessage)

                .icon(icon)

                .anchor(0.5f, 1.0f));

 

        mMap.addMarker(new MarkerOptions()

                .gridPoint(MapProjection.getDefault().toGridPoint(55.946060000000, -4.576470000000))

                .title("Finish point")

//                    .snippet(locationMessage)

                .icon(icon)

                .anchor(0.0f, 0.0f));

 

   }

 

 

Code from app:

final Marker m = mMap.addMarker(new MarkerOptions()

                                .title(name)

                                .snippet(sID)

                                .gridPoint(MapProjection.getDefault().toGridPoint(lat, lon))

                                .anchor(0.5f, 1.0f)

//.icon(BitmapDescriptorFactory.fromBitmap(bitmap))

                );

**Comment by jsr-software** [comment]
Pull request for the bearing code is now in the main repo. Feel free to clone / pull from it for this fix until such time as the jar is redeployed.
