### ISSUE TITLE
Documentation on creating ostiles

### ISSUE THREAD

**Issue by codebrane** [OrdnanceSurvey/openspace-android-sdk#11]
Is there any documentation on how to create compatible ostiles databases? I took the sample sx88.tif and ran it through gdal2tiles to get 200x200 pixel tiles and they are in the correct format database with a product code of 50K. I just get 'failed to draw any tiles'.

I don't know what MapLayer.layerCode is for as it doesn't reference anything in the sample.ostiles database from the iOS demo app for OV0, OV1, OV2.

Would the OS have sample scripts for slicing something like sx88.tif?

**Comment by jskeates** [comment]
Hey @codebrane, a list of product codes is available on [our site](https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/web-services/os-openspace/os-openspace-pro-technical.html#faq5) in the OpenSpace FAQs. They can also be found in the code in [MapLayers.java](https://github.com/OrdnanceSurvey/openspace-android-sdk/blob/c6b10bec6ce1486d88c859d101bf038125f75877/OSMapAndroid/src/main/java/uk/co/ordnancesurvey/android/maps/MapLayer.java#L72). Hope this helps!

**Comment by codebrane** [comment]
thanks @jskeates. That's a good page. According to the FAQ, 50K has a resolution of 5 metres per pixel (mpp). sx88.tif is a 20kmx20km grid square so it's 4000x4000 pixels. That explains that bit, perfect. Thanks for that.

The FAQ says each product is provided at 2 resolutions, so 50K is 5mpp and 10mpp. I'm not sure what 'provided' means. I only have a 5mpp tif from the OS sample data. Do I have to create my own 10mpp version in order to get the SDK to display the sample data? Or will the SDK work with just one zoom level (or two?) generated from the 5mpp sample tif?

**Comment by codebrane** [comment]
I think I've been chasing a red herring @jskeates when I've been using gdal2tiles. I think the OS maps don't conform to standard tiling levels. I see from the page 50K only has 2, where gdal2tiles generates 6 from the sample tif.

Is it just a case of taking the 4000x4000 tif (5mpp) and slicing this into 200x200 pixel tiles with ImageMagick (instead of gdal2tiles). This would form zoom_level 2 in the database. Then downscale the tif to 2000x2000 (10mpp) and tile that to 200x200 tiles and that would be zoom_level 1 in the database?

**Comment by codebrane** [comment]
I've even resorted to ImageMagick to create 200x200 pixel tiles in columns and rows for a single zoom level for product code 50K and all the SDK says is 'failed to draw any tiles!'

**Comment by codebrane** [comment]
[This page](https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/web-services/os-ondemand/configuring-wmts.html) says each tile for 50K must be 5 pixels per metre and each tile must be 1000 metres. The source raster is sx99.tif (sample from the OS) which is 4000x4000, so 200x200 tiles match the spec perfectly. And yet the SDK fails to draw anything.

Is there other information to be had? I've checked the ostiles database format against the sample.ostiles that comes with the iOS demo app and the format is correct. The tile resolution is correct and product code is correct. Why would the SDK fail to draw the tiles?

**Comment by codebrane** [comment]
![0](https://cloud.githubusercontent.com/assets/40967/9995256/21991484-6079-11e5-9022-33eae5f78e1c.png)
the above is zoom_level 1, tile_column 0, tile_row 0. It's 200x200 and there are 20 of them in column 20. I think this matches the specification. There are 20 columns, each with 20 rows and they are in the database in the correct format. The SDK fails to draw them.

**Comment by jskeates** [comment]
@codebrane Have you double checked the [OSTiles spec](https://github.com/OrdnanceSurvey/openspace-sdk-resources/blob/master/ostiles_spec.md), just in case you're missing something?

**Comment by codebrane** [comment]
@jskeates yep I've double and triple checked the spec. The ostiles db I created is identical to sample.ostiles in format. The tiles are product code 50K, 200 x 200 pixels, 5 metres per pixel, 1000 x 1000 metres, 400 tiles, so they conform to the spec exactly. SDK fails to draw any.
The only difference I can see between OV0 and my 50K tiles are my tiles have an alpha channel (RGBA) while the OV0 ones don't (RGB). Surely that wouldn't cause the SDK to fail?

**Comment by codebrane** [comment]
@jskeates there isn't any documentation on zoom levels so I only have one. OV0 only has one zoom level too and the SDK displays that product. Is there anyone could check my ostiles database? That would prolly nail the issue straight away!

**Comment by codebrane** [comment]
So I worked it out. Would have been good if the ostiles spec said the bounding boxes are for eastings/northings

**Comment by jskeates** [comment]
@codebrane Glad you worked it out! I'll add that to the spec now.
