### ISSUE TITLE
Getting 1:25k map layer- question

### ISSUE THREAD

**Issue by tayldn** [OrdnanceSurvey/openspace-android-sdk#4]
Hi- we are having problem getting the 1:25k map layer.  Can you help?

DETAIL:

I have implemented MapFragment in app and init OSMap with custom webTileSource with commercial key.

As in demo app I use:

 

private final String OS_API_KEY = "/*My commercial key*/";

                private final boolean OS_IS_PRO = true;

private final String[] OS_LAYERS_TYPE = {"SV", "SVR", "25K", "25KR", "50K", "50KR", "250K", "250KR", "MS", "MSR"};

 

                private void initMap() {

SupportMapFragment mf = ((SupportMapFragment) getFragmentManager().findFragmentById(R.id.map_fragment));

                               mMap = mf.getMap();

                               //create list of tileSources

                               ArrayList<OSTileSource> sources = new ArrayList<OSTileSource>();

                 //create web tile source with API details

                               sources.add(mMap.webTileSource(OS_API_KEY, OS_IS_PRO, OS_LAYERS_TYPE));

                               mMap.setTileSources(sources);

                }

 

I have tested app with different variants of Products types, but 25k product isn’t use.

For testing I have changed my commercial key to get errors in Logcat.  Error for example:

    Failed to fetch tile  java.io.FileNotFoundException: https://osopenspacepro.ordnancesurvey.co.uk/osmapapi/ts?FORMAT=image/png&SERVICE=WMS&VERSION=1.1.1&EXCEPTIONS=application/vnd.ogc.se_inimage

&SRS=EPSG:27700&STYLES=&REQUEST=GetMap&KEY=MY_COMMERCIAL_KEY&appId=com.roadtour.outdoorsgb&WIDTH=200&HEIGHT=200&BBOX=235000.0,150000.0,240000.0,155000.0&LAYERS=25&PRODUCT=250K

This error I can get for all products such as 50KR, 250KR, SVR, but I cannot get this error for 25K map. App is downloading SV/SVR tiles after 50K.

May be it is bad variant for checking, but … how I can check where is problem – in my code / in your library /on your server ?

**Comment by jsr-software** [comment]
The 25K product is a PRO key product only. It's not available on the free maps API keys.

Using the fragment in XML does not allow you to set the options on the map prior to inflation / instantiation so it will start with the default mapping stack.

The OSMapOptions object is a public field on the fragment and as such can be changed for a custom one (using different products or PRO key set up), however it is possible that this would cause some unexpected behaviour as the underlying rendering accommodates a change.

We always use the MapFragment as in the code above and tend not to use the XML inflation approach as we need the customisation on our own OS apps.
