### ISSUE TITLE
Latest version code

### ISSUE THREAD

**Issue by OpenTracking** [OrdnanceSurvey/openspace-android-sdk#6]
Would it be possible to update the repository with settings that fix this error and have been tested with the SDK. I've just downloaded the Android Studio and open the project.  As a newbie to app development not confident enough to get the changes right.

Many thanks for your help

Error:The project is using an unsupported version of the Android Gradle plug-in (0.6.3). The recommended version is 1.0.0.

Starting with version 0.9.0 incompatible changes were introduced in the build language.
Please read the migration guide to learn how to update your project.
<a href="fixGradleElements">Open migration guide, fix plug-in version and sync project</a>

**Comment by jsr-software** [comment]
The SDK will happily run on the latest version of Gradle with out much in the way of changes the SDK code.

From the error above it just looks like an out of date setting with regards to the Gradle plugin

Can you do one two things for me:
1. State which project you're trying to open to receive the error. The SDK build is currently ant based but the example projects are in Gradle.
2. If it is not one of the example projects then please paste your project build.gradle file in a comment here please and I will take a look over it in case of any issues with the build file.

**Comment by OpenTracking** [comment]
Hi there
Thanks for the reply... it is the sample projects that I am trying to get to build. The sample projects that appear to be out of date for the latest Android Studio and Gradle downloads are the main demo and marker overlay.

android-sdk-mapping-demo/OSMappingDemo/OSMappingDemo/build.gradle
android-sdk-demo-map-overlays/OSMapOverlays/OSMapOverlays/build.gradle

Can you please elaborate on your comment "much in the way of changes to the SDK code." Being a total novice to Android development I don't know where to start with any changes and it would really beneficial if the code samples and SDK were brought up to date. ant and Gradle mean nothing to me just yet!

Many thanks

**Comment by jsr-software** [comment]
No worries,

changing the gradle plugin version (in build.gradle) to the following:
`classpath 'com.android.tools.build:gradle:1.0.0'`
should get you building on the latest version of the android gradle plugin and remove the error stated above.

This should allow you to build and run the sample projects (with a valid registered api key).

Please note that openspace api keys need to have the android apps registered against them. Please contact the openspace admin team to register apps against api keys.

**Comment by OpenTracking** [comment]
That's great - also needed to change these two lines in the same file.

compileSdkVersion 19
buildToolsVersion "19.1.0"
