### ISSUE TITLE
I can not display Vector Map Local on Android app.

### ISSUE THREAD

**Issue by kikyoungkwon** [OrdnanceSurvey/openspace-android-sdk#7]
I would like to test Vector Map Local layers on our Android app, so registered to OpenSpace Pro trial and put the licence key to the below code.

ArrayList<OSTileSource> sources = new ArrayList<OSTileSource>();
String[] overviewMappingLayers = new String[] {
    // Users with an appropriate commercial or direct licence can also select to use these products:
    "VML", // Vector Map Local
    "VMLR", // Vector Map Local resampled
    "25K", // 1:25k
    "25KR", // 1:25k resampled
    "50K", // 1:50k
    "50KR" // 1:50k resampled
};
sources.add(mMap.webTileSource(OS_PRO_API_KEY, true, overviewMappingLayers));
mMap.setTileSources(sources);

However, I keep getting the below errors with ugly OS map layers.

V/GLMapRenderer﹕ Failed to draw any tiles!
V/GLMapRenderer﹕ Failed to draw any tiles!
V/GLMapRenderer﹕ Failed to draw any tiles!
V/GLMapRenderer﹕ Failed to draw any tiles!
V/GLMapRenderer﹕ Failed to draw any tiles!
V/GLMapRenderer﹕ Failed to draw any tiles!
V/GLMapRenderer﹕ Failed to draw any tiles!

Is it not possible to display Vector Map Local layers with OpenSpace Pro trial licence or have I made any mistakes in my code?

Thanks in advance.

**Comment by jsr-software** [comment]
Hi, thanks for raising this. 

I'll run a test app on your api key details and see if there is a configuration issue at our end and let you know the outcome shortly.

**Comment by jsr-software** [comment]
Hello,
It's not a configuration issue but a quirk of the products set up for pro keys. You need to set the OSMapOptions object on the MapFragment at construction time so it cannot be inflated from xml else it reverts back to the default maps or in some cases causes an application crash.

The code snippet below is the smallest activity that will render the requested layers:

```
import android.app.Activity;
import android.os.Bundle;

import java.util.ArrayList;

import uk.co.ordnancesurvey.android.maps.MapFragment;
import uk.co.ordnancesurvey.android.maps.OSMap;
import uk.co.ordnancesurvey.android.maps.OSMapOptions;
import uk.co.ordnancesurvey.android.maps.OSTileSource;

public class MainActivity extends Activity {

    private final static String OS_API_KEY = "key-here";
    private final static boolean OS_IS_PRO = true;
    private final static String[] LAYERS = new String[] { "VML", "VMLR", "25K", "25KR","50K","50KR" };

    private OSMap mMap;
    private MapFragment mMapFragment;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        OSMapOptions options = new OSMapOptions();
        options.products(LAYERS);

        mMapFragment = new MapFragment(options);
        getFragmentManager()
                .beginTransaction()
                .add(android.R.id.content, mMapFragment, "MAP_TAG")
                .commit();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mMap = mMapFragment.getMap();

        //create web tile source with API details
        ArrayList<OSTileSource> sources = new ArrayList<>();
        sources.add(mMap.webTileSource(OS_API_KEY, OS_IS_PRO, LAYERS));
        mMap.setTileSources(sources);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
    }
}
```

You will still need to add the correct permissions and feature tags to the manifest.

Please let me know how you get on.

**Comment by tayldn** [comment]
Hi Jim,

Who is it we should contact for iOS SDK Openspace issues?

Regards, 

Daniel Taylor
www.outdoorsgps.com
0208 819 1331
07912 149681

**Comment by jsr-software** [comment]
@tayldn If you contact the Openspace support team they will route the query through to the relevant support team. I can't give you a name direct as it depends which member of the team gets the request.

**Comment by tayldn** [comment]
Thanks!

Regards, 

Daniel Taylor
www.outdoorsgps.com
0208 819 1331
07912 149681

**Comment by kikyoungkwon** [comment]
@jsr-software Thanks for your help. I managed to display vector maps layers, however if I zoom in close to roads, the map is blurred and not clear, and also I keep getting same messages below.

V/GLMapRenderer﹕ Failed to draw any tiles!
V/GLMapRenderer﹕ Failed to draw any tiles!
V/GLMapRenderer﹕ Failed to draw any tiles!
V/GLMapRenderer﹕ Failed to draw any tiles!

![os1](https://cloud.githubusercontent.com/assets/1456659/7722820/8d92aa2e-fedb-11e4-981f-45c7ced11286.gif)

Is there any way to see the map layers clearly??

In addition, If I zoom out, normal OS maps layers are displayed and very slow like the below.

![os2](https://cloud.githubusercontent.com/assets/1456659/7722821/8d996b52-fedb-11e4-87fd-487050c7eee9.gif)

Is there any way to keep displaying vector maps layers??

**Comment by jsr-software** [comment]
@kikyoungkwon The map will attempt to render the tiles for the closest tile layer it has data configuration for from it's current zoom level.

So if you only set up a single tile layer (for example 25K) it will attempt to render lots of tiles when zoomed out giving the slow performance and stretch tiles (giving the blurry effect) when zoomed in. 

The way the SDK was configured there is an expectation to give a full stack of backdrop mapping across the zoom levels. So you may need to present a different mapping product for zoom levels that don't support the vector map layers.

**Comment by jsr-software** [comment]
@kikyoungkwon I'm closing this issue as you state you can now view the requested maps. For other queries please open an issue on the forum.

**Comment by kikyoungkwon** [comment]
Thanks.
