### ISSUE TITLE
Blank Map

### ISSUE THREAD

**Issue by Nomester** [OrdnanceSurvey/openspace-android-sdk#8]
Hi, I think I'm probably just doing something stupid.  I just did a basic lift of the demo app, I've got my API key and registered the test app id.  There are no error messages in the log.

Anyhoo, when I run the app it starts up on the phone and then displays a blank screen.

My onCreate:

    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    MapFragment mapFragment = ((MapFragment) getFragmentManager().findFragmentById(R.id.map_fragment));

    mMap = mapFragment.getMap();

    //create list of tileSources
    ArrayList<OSTileSource> sources = new ArrayList<OSTileSource>();

    //create web tile source with API details
    sources.add(mMap.webTileSource(OS_API_KEY, OS_IS_PRO, null));
    mMap.setTileSources(sources);

and my xml;

    <fragment
      android:id="@+id/map_fragment"
      android:name="uk.co.ordnancesurvey.android.maps.MapFragment"
      android:layout_width="match_parent"
      android:layout_height="match_parent" />

I did wonder if there was a combination of settings on the phone that was required, but I've fiddled with that too!

Cheers.

**Comment by jsr-software** [comment]
Hi @Nomester,

It looks like you are following to guide code well enough but it should at least show the default map stack. 

It could be a number of items:

1) Have you got all the permissions needed in the manifest (I always miss at least one on setting up a new project)? 

The minimum to display maps are the following:

   ```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

2) It could be a bad API key config (I will check with the support team to eliminate this in the morning when I'm back in the office by running a test against your API key).

3) It could be a quirk of a Pro key and product combination. Some product and key combinations mean that the MapFragment has to be set up manually and cannot be inflated from the xml correctly. I can't tell if your key is a pro one from the code snippet.

Take a look at the following issue:
https://github.com/OrdnanceSurvey/openspace-android-sdk/issues/7

This issue contains a self contained Activity code snippet that should display the products in the array. Just change the key, the PRO key boolean and the products to the following array contents and it should display the default maps:

```
//default stack
{"SV","SVR","50K","50KR","250K","250KR","MS","MSR","OV2","OV1","OV0"}
```

**Comment by jsr-software** [comment]
Hi @Nomester,

I ran a test using your key here this morning and it looks like you're experiencing the same issue with PRO keys in that you cannot inflate the fragment from xml and need to do it in code.

The code snippet referenced above will display maps using the credentials you have.

Let me know how you get on.

**Comment by Nomester** [comment]
Hi Jim

I have the correct perms in the manifest, do I need to change the xml file?

I’m now getting a NPE at the following line.

sources.add(mMap.webTileSource(OS_API_KEY, OS_IS_PRO, LAYERS));


Cheers,

Naomi


public class MainActivity extends Activity implements OSMap.OnMapClickListener {

  private final static String OS_API_KEY = "zlucIa3wiaqiuDro4yoEM174tOuTHLeb";

  private final static boolean OS_IS_PRO = false;

  private final static String[] LAYERS = new String[] { "SV","SVR","50K","50KR","250K","250KR","MS","MSR","OV2","OV1","OV0" };

  private final static String LOGTAG = MainActivity.class.getSimpleName();

  private OSMap mMap;
  private MapFragment mapFragment;

  @Override
  protected void onCreate(Bundle savedInstanceState) {

    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    OSMapOptions options = new OSMapOptions();
    options.products(LAYERS);

    mapFragment = new MapFragment(options);
    getFragmentManager()
        .beginTransaction()
        .add(android.R.id.content, mapFragment, "MAP_TAG")
        .commit();

    mMap = mapFragment.getMap();

    //create web tile source with API details
    ArrayList<OSTileSource> sources = new ArrayList<>();
    sources.add(mMap.webTileSource(OS_API_KEY, OS_IS_PRO, LAYERS));
    mMap.setTileSources(sources);

  }

}

On 12 Jun 2015, at 10:10, Jim Reeves <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Nomester<https://github.com/Nomester>,

I ran a test using your key here this morning and it looks like you're experiencing the same issue with PRO keys in that you cannot inflate the fragment from xml and need to do it in code.

The code snippet referenced above will display maps using the credentials you have.

Let me know how you get on.

**Comment by Nomester** [comment]
Hi Jim

I’ve also checked out the following;

https://github.com/OrdnanceSurvey/android-sdk-demo-google-maps-android-conversion.git

and run it and I get the same blank map.

So basically if I use the fragment route, then the map fragment doesn’t inflate and if I build the fragment manually in code when I do getMap() then the map is null and it throws a NPE when I try to add it to the array of OSTileSource.

Next steps?

Also as we’re evaluating the product before we pay for a full license for it we are slightly concerned that the evaluation license is not displaying the same behaviour as the pro version, so limited point in evaluating as it’s going to be different?

Regards,
Naomi



Hi @Nomester<https://github.com/Nomester>,

I ran a test using your key here this morning and it looks like you're experiencing the same issue with PRO keys in that you cannot inflate the fragment from xml and need to do it in code.

The code snippet referenced above will display maps using the credentials you have.

Let me know how you get on.

**Comment by jsr-software** [comment]
Hi @Nomester 

I've removed your API key from the above comments.

Looking at the source code you've given you are setting a layout xml and then placing the fragment into the root of the view (android.R.id.content) and not into any container view in your custom layout.

You are getting a null OSMap object back from your call to getMap() as this is not initialised inside onCreate() of the MapFragment and will be available in onResume()

Can you try the following (an adjustment of your given code):

```
public class MainActivity extends Activity {

    private final static String OS_API_KEY = "API_KEY_HERE";
    private final static boolean OS_IS_PRO = false;
    private final static String[] LAYERS = new String[]
            {"SV","SVR","50K","50KR","250K","250KR","MS","MSR","OV2","OV1","OV0"};

    private OSMap mMap;
    private MapFragment mMapFragment;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        OSMapOptions options = new OSMapOptions();
        options.products(LAYERS);

        mMapFragment = new MapFragment(options);
        getFragmentManager()
                .beginTransaction()
                .add(android.R.id.content, mMapFragment, "MAP_TAG")
                .commit();
    }

    @Override
    protected void onResume() {
        super.onResume();
        // getMap() returns null prior to the map fragment being resumed.
        mMap = mMapFragment.getMap();

        //create web tile source with API details
        ArrayList<OSTileSource> sources = new ArrayList<>();
        sources.add(mMap.webTileSource(OS_API_KEY, OS_IS_PRO, LAYERS));
        mMap.setTileSources(sources);
    }
}

```

Let me know how you get on.

**Comment by Nomester** [comment]
Hi Jim

This is the code I’m using now;

@Override
protected void onCreate(Bundle savedInstanceState) {

    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    OSMapOptions options = new OSMapOptions();
    options.products(LAYERS);

    mapFragment = new MapFragment(options);

    getFragmentManager()
        .beginTransaction()
        .add(R.id.map_fragment, mapFragment, "MAP_TAG")
        .commit();

    setUpMapIfNeeded();

    setUpSources();
  }

  private void setUpMapIfNeeded() {
    if (mMap == null) {
      // Try to obtain the map from the SupportMapFragment.
      mMap = mapFragment.getMap();
      // Check if we were successful in obtaining the map.
      if (mMap != null) {
        // here you can setup the map the way you want
        Log.v(LOGTAG, "Map is Not Null");
      } else {
        Log.v(LOGTAG, "Map is Null");
      }
    }
  }

  private void setUpSources() {
    ArrayList<OSTileSource> sources = new ArrayList<>();
    sources.add(mMap.webTileSource(OS_API_KEY, OS_IS_PRO, LAYERS));
    mMap.setTileSources(sources);
  }

  @Override
  protected void onResume() {
    super.onResume();
    setUpMapIfNeeded();
    setUpSources();
  }

and my xml looks like:

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:paddingLeft="@dimen/activity_horizontal_margin"
                android:paddingRight="@dimen/activity_horizontal_margin"
                android:paddingTop="@dimen/activity_vertical_margin"
                android:paddingBottom="@dimen/activity_vertical_margin"
                tools:context=".MainActivity">

  <FrameLayout
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:id="@+id/map_fragment"></FrameLayout>

</RelativeLayout>

I’m still getting a null OSMap. Could it be something else like the ‘phone settings or something? I could zip up my test project and send it to you?

On 17 Jun 2015, at 14:10, Jim Reeves <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Nomester<https://github.com/Nomester>

I've removed your API key from the above comments.

Looking at the source code you've given you are setting a layout xml and then placing the fragment into the root of the view (android.R.id.content) and not into any container view in your custom layout.

You are getting a null OSMap object back from your call to getMap() as this is not initialised inside onCreate() of the MapFragment and will be available in onResume()

Can you try the following (an adjustment of your given code):

public class MainActivity extends Activity {

    private final static String OS_API_KEY = "API_KEY_HERE";
    private final static boolean OS_IS_PRO = false;
    private final static String[] LAYERS = new String[]
            {"SV","SVR","50K","50KR","250K","250KR","MS","MSR","OV2","OV1","OV0"};

    private OSMap mMap;
    private MapFragment mMapFragment;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        OSMapOptions options = new OSMapOptions();
        options.products(LAYERS);

        mMapFragment = new MapFragment(options);
        getFragmentManager()
                .beginTransaction()
                .add(android.R.id.content, mMapFragment, "MAP_TAG")
                .commit();
    }

    @Override
    protected void onResume() {
        super.onResume();
        // getMap() returns null prior to the map fragment being resumed.
        mMap = mMapFragment.getMap();

        //create web tile source with API details
        ArrayList<OSTileSource> sources = new ArrayList<>();
        sources.add(mMap.webTileSource(OS_API_KEY, OS_IS_PRO, LAYERS));
        mMap.setTileSources(sources);
    }
}



Let me know how you get on.

**Comment by jsr-software** [comment]
@Nomester I can't see anything immediately obvious from  Do you have your project on a github repo that I can clone from? The reason is we cannot accept files in from outside the business for security reasons. 

If not I will take a look another look with the code above when I'm back in the office in the morning and perhaps post a small project up for you to clone from.

**Comment by Nomester** [comment]
Github repo https://github.com/Nomester/mapTest

Let me know how you get on, I’m sure it’s something dumb.

Thanks,

On 18 Jun 2015, at 21:11, Jim Reeves <notifications@github.com<mailto:notifications@github.com>> wrote:


@Nomester<https://github.com/Nomester> I can't see anything immediately obvious from Do you have your project on a github repo that I can clone from? The reason is we cannot accept files in from outside the business for security reasons.

If not I will take a look another look with the code above when I'm back in the office in the morning and perhaps post a small project up for you to clone from.

**Comment by jskeates** [comment]
@Nomester Your API key that ends in "*HLeb*" is Openspace Pro, so `OS_IS_PRO` should be set to `true`
